/*
 * Copyright 2023 CodeThink Technologies and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cn.codethink.xiaoming.event;

import cn.codethink.xiaoming.Subject;
import cn.codethink.xiaoming.api.BotApiFactory;
import cn.codethink.xiaoming.cause.Cause;
import cn.codethink.xiaoming.time.Time;

/**
 * <h1>Cancellation State Operation</h1>
 *
 * <p>Cancellation state operation is operation in the
 * event cancellation state, generated by calling the
 * {@link CancellableEvent#setCancelled(boolean, Cause, Subject)}. </p>
 *
 * @author Chuanwise
 */
public interface CancellationStateOperation
        extends Cause {

    /**
     * Construct a cancellation state operation.
     *
     * @param cancelled cancelled
     * @param event     event
     * @param cause     cause
     * @param subject   subject
     * @return cancellation state operation
     * @throws NullPointerException event, cause or subject is null
     */
    static CancellationStateOperation of(boolean cancelled, Event event, Cause cause, Subject subject) {
        return BotApiFactory.getBotApi().getCancellationStateOperation(cancelled, event, cause, subject);
    }

    /**
     * Query if the operation is cancellation.
     *
     * @return if the operation is cancellation
     */
    boolean isCancelled();

    /**
     * Get subject.
     *
     * @return subject
     */
    Subject getSubject();

    /**
     * Get time.
     *
     * @return time
     */
    Time getTime();

    /**
     * Get event.
     *
     * @return event
     */
    Event getEvent();
}
