/*
 * Copyright 2023 CodeThink Technologies and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cn.codethink.xiaoming.event;

import cn.codethink.xiaoming.Subject;
import cn.codethink.xiaoming.api.BotApiFactory;
import cn.codethink.xiaoming.cause.Cause;
import cn.codethink.xiaoming.time.Time;

/**
 * <h1>Interception State Operation</h1>
 *
 * <p>Interception state operation is operation in the
 * event interception state, generated by calling the
 * {@link Event#setIntercepted(boolean, Cause, Subject)}. </p>
 *
 * @author Chuanwise
 */
public interface InterceptionStateOperation
        extends Cause {

    /**
     * Construct a interception state operation.
     *
     * @param intercepted intercepted
     * @param event       event
     * @param cause       cause
     * @param subject     subject
     * @return interception state operation
     * @throws NullPointerException event, cause or subject is null
     */
    static InterceptionStateOperation of(boolean intercepted, Event event, Cause cause, Subject subject) {
        return BotApiFactory.getBotApi().getInterceptionStateOperation(intercepted, event, cause, subject);
    }

    /**
     * Get event.
     *
     * @return event
     */
    Event getEvent();

    /**
     * Query if the operation is interception.
     *
     * @return if the operation is interception
     */
    boolean isIntercepted();

    /**
     * Get subject.
     *
     * @return subject
     */
    Subject getSubject();

    /**
     * Get time.
     *
     * @return time
     */
    Time getTime();
}
