package cn.chuanwise.xiaoming.interactor;

public enum InteractResult {
    INTERACTED,
    INTERACTED_BUT_FALSE,
    ERROR,
    LACK_PERMISSIONS,
    ILLEGAL_SCOPE,
    LACK_GROUP_TAGS,
    TIMEOUT_CANCELLED,
    INTERRUPTED,
    EXIT,
    EVENT_CANCELLED,
    LACK_ACCOUNT_TAGS,
    ILLEGAL_FORMAT,
    PARSE_FAILED,
    ILLEGAL_TYPE,
    ILLEGAL_PARAMETER,
    QUITE_MODE_DENIED,
    NOT_ENABLE_YET,
    ACCOUNT_BLOCK_PLUGIN,
}
