package cn.chuanwise.xiaoming.utility;

import cn.chuanwise.utility.StaticUtility;

public class CommandWords extends StaticUtility {
    public static final String
            GLOBAL = "(全局|公共|global)",
            ECHO = "(回声|回响|echo)",
            HEAD = "(头|开头|head)",
            RELOAD = "(重载|重加载|reload)",
            LOOK = "(查看|罗列|list|look)",
            NEW = "(创建|新增|新建|新|new)",
            ADD = "(添加|增加|增添|add)",
            QQ = "(qq|QQ|Qq|qQ)",
            REMOVE = "(删除|删掉|卸载|删|取消|移除|去除|减少|remove|delete)",
            PERSONAL = "(我的|我|私人|私有|用户|me|my|personal|private)",
            OTHERS = "(他人|别人|他|别人|his|her|its)",
            PLUGIN = "(插件|plugin|plugins)",
            PERMISSION_GROUP = "(权限组|permissiongroup)",
            PERMISSION = "(权限|permission)",
            ALIAS = "(别名|昵称|绰号|备注|alias)",
            CONFIRM = "(确定|确认|confirm)",
            COMMAND = "(指令|command)",
            USER = "(用户|玩家|好友|user)",
            XIAOMING = "(小明|xiaoming)",
            STATUS = "(状态|status)",
            HELP = "(帮助|说明|help)",
            INFO = "(信息|info)",
            GROUP = "(群聊|群|group)",
            RECORD = "(记录|record)",
            TAG = "(标记|tag)",
            PRIVATE = "(私聊|私|private)",
            INTERACTOR = "(交互器|interactor)",
            ILLEGAL = "(非法|违规|禁用|禁止|illegal)",
            DISABLE = "(关闭|禁用|禁止|disable)",
            OPTIMIZE = "(优化|optimize)",
            ENABLE = "(启用|启动|打开|enable)",
            ACCOUNT = "(账户|account)",
            THIS = "(当前|本|this)",
            BLOCK = "(屏蔽|block)",
            CANCEL = "(取消|撤回|cancel|un)",
            MERGE = "(合并|merge)",
            LIMIT = "(限制|limit)",
            CALL = "(调用|召唤|call|invoke)",
            TASK = "(任务|task)",
            UNBLOCK = CANCEL + BLOCK,
            RECENT = "(近期|最近|last|recent)",
            EXCEPTION = "(异常|exception)",
            CLEAR = "(清空|清除|clear)",
            SAVE = "(保存|save)",
            PERIOD = "(周期|period)",
            SEARCH = "(查|查询|search)",
            ERROR = "(错误|error)",
            MESSAGE = "(消息|信息|message|报告|report)",
            EDIT = "(修改|编辑|edit|modify)",
            SET = "(设置|set)",
            USE = "(使用|use)",
            RECEPTION = "(接待员|招待员|接待者|招待者|receptionist)",
            AUTO = "(自动|auto)",
            CONFIGURATE = "(配置|configurate|config)",
            ALLOW = "(允许|准许|批准|allow)",
            STRANGE = "(陌生|奇怪|strange)";
}
