log4j.rootLogger=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=com.chuanwise.xiaoming.host.log.ColorPatternLayout

log4j.appender.stdout.encoding=GBK

# Pattern to output the caller's file name and line number.
log4j.appender.INFO=org.apache.log4j.DailyRollingFileAppender
log4j.appender.INFO.File=./logs/lastest.log
log4j.appender.INFO.MaxFileSize=100KB

log4j.appender.INFO.encoding=UTF-8

# Keep one backup file
log4j.appender.INFO.MaxBackupIndex=1
log4j.appender.INFO.layout=com.chuanwise.xiaoming.host.log.ColorPatternLayout
log4j.appender.INFO.layout.ConversionPattern=%p %t %c - %m%n