package com.chuanwise.xiaoming.api.util;

public class CommandWords {
    public static final String GLOBAL_REGEX = "(全局|公共|global)";
    public static final String RELOAD_REGEX = "(重载|重加载|reload)";
    public static final String LOOK_REGEX = "(查看|罗列|list|look)";
    public static final String NEW_REGEX = "(新增|新建|增加|增添|添加|新|add|new)";
    public static final String REMOVE_REGEX = "(删除|删掉|卸载|删|取消|移除|去除|减少|remove|delete)";
    public static final String PERSONAL_REGEX = "(我的|我|私人|私有|用户|me|my|personal|private)";
    public static final String OTHER_REGEX = "(他人|别人|他|别人|his|her|its)";
    public static final String PLUGIN_REGEX = "(插件|plugin|plugins)";
    public static final String PERMISSION_GROUP_REGEX = "(权限|权限组|permission)";
    public static final String ALIAS_REGEX = "(别名|昵称|绰号|备注|alias)";
    public static final String CONFIRM_REGEX = "(确定|确认|confirm)";
    public static final String USER_REGEX = "(用户|玩家|好友|user)";
    public static final String XIAOMING_REGEX = "(小明|xiaoming)";
    public static final String STATUS_REGEX = "(状态|status)";
    public static final String HELP_REGEX = "(帮助|说明|help)";
    public static final String GROUP_REGEX = "(群聊|群|group)";
    public static final String PRIVATE_REGEX = "(私聊|私|private)";
    public static final String INTERACTOR_REGEX = "(交互器|interactor)";
    public static final String ILLEGAL_REGEX = "(非法|违规|禁用|禁止|illegal)";
    public static final String DISABLE_REGEX = "(关闭|禁用|禁止|disable)";
    public static final String OPTIMIZE_REGEX = "(优化|optimize)";
    public static final String ENABLE_REGEX = "(启用|启动|打开|enable)";
    public static final String ACCOUNT_REGEX = "(账户|account)";
    public static final String THIS_REGEX = "(当前|本|this)";
    public static final String BLOCK_REGEX = "(屏蔽|block)";
    public static final String CANCEL_REGEX = "(取消|撤回|cancel|un)";
    public static final String MERGE_REGEX = "(合并|merge)";
    public static final String LIMIT_REGEX = "(限制|limit)";
    public static final String CALL_REGEX = "(调用|召唤|call|invoke)";
    public static final String UNBLOCK_REGEX = CANCEL_REGEX + BLOCK_REGEX;
    public static final String RECENT_REGEX = "(近期|最近|last|recent)";
    public static final String EXCEPTION_REGEX = "(异常|exception)";
    public static final String CLEAR_REGEX = "(清空|清除|clear)";
    public static final String SAVE_REGEX = "(保存|save)";
    public static final String SEARCH_REGEX = "(查|查询|search)";
    public static final String ERROR_REGEX = "(错误|error)";
    public static final String MESSAGE_REGEX = "(消息|信息|message|报告|report)";
    public static final String EDIT_REGEX = "(修改|编辑|edit|modify)";
    public static final String USE_REGEX = "(使用|use)";
    public static final String RECEPTION_REGEX = "(接待员|招待员|接待者|招待者|receptionist)";
}
