package cn.codethink.xiaoming.message;

import cn.chuanwise.common.util.Preconditions;
import cn.chuanwise.common.util.StaticUtilities;
import cn.codethink.xiaoming.message.basic.Face;

import java.util.NoSuchElementException;

/**
 * Mirai 相关表情
 *
 * @author Chuanwise
 */
public class MiraiFace
    extends StaticUtilities {
    
    /**
     * 将小明表情转化为 Mirai 表情 Id
     *
     * @param face 小明表情
     * @return Mirai 表情 Id
     */
    @SuppressWarnings("all")
    public static int toMiraiFaceId(Face face) {
        Preconditions.objectNonNull(face, "face");
    
        switch (face) {
            case JING_YA:
                return net.mamoe.mirai.message.data.Face.JING_YA;
            case PIE_ZUI:
                return net.mamoe.mirai.message.data.Face.PIE_ZUI;
            case SE:
                return net.mamoe.mirai.message.data.Face.SE;
            case FA_DAI:
                return net.mamoe.mirai.message.data.Face.FA_DAI;
            case DE_YI:
                return net.mamoe.mirai.message.data.Face.DE_YI;
            case LIU_LEI:
                return net.mamoe.mirai.message.data.Face.LIU_LEI;
            case HAI_XIU:
                return net.mamoe.mirai.message.data.Face.HAI_XIU;
            case BI_ZUI:
                return net.mamoe.mirai.message.data.Face.BI_ZUI;
            case SHUI:
                return net.mamoe.mirai.message.data.Face.SHUI;
            case DA_KU:
                return net.mamoe.mirai.message.data.Face.DA_KU;
            case GAN_GA:
                return net.mamoe.mirai.message.data.Face.GAN_GA;
            case FA_NU:
                return net.mamoe.mirai.message.data.Face.FA_NU;
            case TIAO_PI:
                return net.mamoe.mirai.message.data.Face.TIAO_PI;
            case ZI_YA:
                return net.mamoe.mirai.message.data.Face.ZI_YA;
            case WEI_XIAO:
                return net.mamoe.mirai.message.data.Face.WEI_XIAO;
            case NAN_GUO:
                return net.mamoe.mirai.message.data.Face.NAN_GUO;
            case KU:
                return net.mamoe.mirai.message.data.Face.KU;
            case ZHUA_KUANG:
                return net.mamoe.mirai.message.data.Face.ZHUA_KUANG;
            case TU:
                return net.mamoe.mirai.message.data.Face.TU;
            case TOU_XIAO:
                return net.mamoe.mirai.message.data.Face.TOU_XIAO;
            case KE_AI:
                return net.mamoe.mirai.message.data.Face.KE_AI;
            case BAI_YAN:
                return net.mamoe.mirai.message.data.Face.BAI_YAN;
            case AO_MAN:
                return net.mamoe.mirai.message.data.Face.AO_MAN;
            case JI_E:
                return net.mamoe.mirai.message.data.Face.JI_E;
            case KUN:
                return net.mamoe.mirai.message.data.Face.KUN;
            case JING_KONG:
                return net.mamoe.mirai.message.data.Face.JING_KONG;
            case LIU_HAN:
                return net.mamoe.mirai.message.data.Face.LIU_HAN;
            case HAN_XIAO:
                return net.mamoe.mirai.message.data.Face.HAN_XIAO;
            case YOU_XIAN:
                return net.mamoe.mirai.message.data.Face.YOU_XIAN;
            case FEN_DOU:
                return net.mamoe.mirai.message.data.Face.FEN_DOU;
            case ZHOU_MA:
                return net.mamoe.mirai.message.data.Face.ZHOU_MA;
            case YI_WEN:
                return net.mamoe.mirai.message.data.Face.YI_WEN;
            case XU:
                return net.mamoe.mirai.message.data.Face.XU;
            case YUN:
                return net.mamoe.mirai.message.data.Face.YUN;
            case ZHE_MO:
                return net.mamoe.mirai.message.data.Face.ZHE_MO;
            case SHUAI:
                return net.mamoe.mirai.message.data.Face.SHUAI;
            case KU_LOU:
                return net.mamoe.mirai.message.data.Face.KU_LOU;
            case QIAO_DA:
                return net.mamoe.mirai.message.data.Face.QIAO_DA;
            case ZAI_JIAN:
                return net.mamoe.mirai.message.data.Face.ZAI_JIAN;
            case FA_DOU:
                return net.mamoe.mirai.message.data.Face.FA_DOU;
            case AI_QING:
                return net.mamoe.mirai.message.data.Face.AI_QING;
            case TIAO_TIAO:
                return net.mamoe.mirai.message.data.Face.TIAO_TIAO;
            case ZHU_TOU:
                return net.mamoe.mirai.message.data.Face.ZHU_TOU;
            case YONG_BAO:
                return net.mamoe.mirai.message.data.Face.YONG_BAO;
            case DAN_GAO:
                return net.mamoe.mirai.message.data.Face.DAN_GAO;
            case SHAN_DIAN:
                return net.mamoe.mirai.message.data.Face.SHAN_DIAN;
            case ZHA_DAN:
                return net.mamoe.mirai.message.data.Face.ZHA_DAN;
            case DAO:
                return net.mamoe.mirai.message.data.Face.DAO;
            case ZU_QIU:
                return net.mamoe.mirai.message.data.Face.ZU_QIU;
            case BIAN_BIAN:
                return net.mamoe.mirai.message.data.Face.BIAN_BIAN;
            case KA_FEI:
                return net.mamoe.mirai.message.data.Face.KA_FEI;
            case FAN:
                return net.mamoe.mirai.message.data.Face.FAN;
            case MEI_GUI:
                return net.mamoe.mirai.message.data.Face.MEI_GUI;
            case DIAO_XIE:
                return net.mamoe.mirai.message.data.Face.DIAO_XIE;
            case AI_XIN:
                return net.mamoe.mirai.message.data.Face.AI_XIN;
            case XIN_SUI:
                return net.mamoe.mirai.message.data.Face.XIN_SUI;
            case LI_WU:
                return net.mamoe.mirai.message.data.Face.LI_WU;
            case TAI_YANG:
                return net.mamoe.mirai.message.data.Face.TAI_YANG;
            case YUE_LIANG:
                return net.mamoe.mirai.message.data.Face.YUE_LIANG;
            case ZAN:
                return net.mamoe.mirai.message.data.Face.ZAN;
            case CAI:
                return net.mamoe.mirai.message.data.Face.CAI;
            case WO_SHOU:
                return net.mamoe.mirai.message.data.Face.WO_SHOU;
            case SHENG_LI:
                return net.mamoe.mirai.message.data.Face.SHENG_LI;
            case FEI_WEN:
                return net.mamoe.mirai.message.data.Face.FEI_WEN;
            case OU_HUO:
                return net.mamoe.mirai.message.data.Face.OU_HUO;
            case XI_GUA:
                return net.mamoe.mirai.message.data.Face.XI_GUA;
            case LENG_HAN:
                return net.mamoe.mirai.message.data.Face.LENG_HAN;
            case CA_HAN:
                return net.mamoe.mirai.message.data.Face.CA_HAN;
            case KOU_BI:
                return net.mamoe.mirai.message.data.Face.KOU_BI;
            case GU_ZHANG:
                return net.mamoe.mirai.message.data.Face.GU_ZHANG;
            case QIU_DA_LE:
                return net.mamoe.mirai.message.data.Face.QIU_DA_LE;
            case HUAI_XIAO:
                return net.mamoe.mirai.message.data.Face.HUAI_XIAO;
            case ZUO_HENG_HENG:
                return net.mamoe.mirai.message.data.Face.ZUO_HENG_HENG;
            case YOU_HENG_HENG:
                return net.mamoe.mirai.message.data.Face.YOU_HENG_HENG;
            case HA_QIAN:
                return net.mamoe.mirai.message.data.Face.HA_QIAN;
            case BI_SHI:
                return net.mamoe.mirai.message.data.Face.BI_SHI;
            case WEI_QU:
                return net.mamoe.mirai.message.data.Face.WEI_QU;
            case KUAI_KU_LE:
                return net.mamoe.mirai.message.data.Face.KUAI_KU_LE;
            case YIN_XIAN:
                return net.mamoe.mirai.message.data.Face.YIN_XIAN;
            case QIN_QIN:
                return net.mamoe.mirai.message.data.Face.QIN_QIN;
            case XIA:
                return net.mamoe.mirai.message.data.Face.XIA;
            case KE_LIAN:
                return net.mamoe.mirai.message.data.Face.KE_LIAN;
            case CAI_DAO:
                return net.mamoe.mirai.message.data.Face.CAI_DAO;
            case PI_JIU:
                return net.mamoe.mirai.message.data.Face.PI_JIU;
            case LAN_QIU:
                return net.mamoe.mirai.message.data.Face.LAN_QIU;
            case PING_PANG:
                return net.mamoe.mirai.message.data.Face.PING_PANG;
            case SHI_AI:
                return net.mamoe.mirai.message.data.Face.SHI_AI;
            case PIAO_CHONG:
                return net.mamoe.mirai.message.data.Face.PIAO_CHONG;
            case BAO_QUAN:
                return net.mamoe.mirai.message.data.Face.BAO_QUAN;
            case GOU_YIN:
                return net.mamoe.mirai.message.data.Face.GOU_YIN;
            case QUAN_TOU:
                return net.mamoe.mirai.message.data.Face.QUAN_TOU;
            case CHA_JIN:
                return net.mamoe.mirai.message.data.Face.CHA_JIN;
            case AI_NI:
                return net.mamoe.mirai.message.data.Face.AI_NI;
            case NO:
                return net.mamoe.mirai.message.data.Face.NO;
            case OK:
                return net.mamoe.mirai.message.data.Face.OK;
            case ZHUAN_QUAN:
                return net.mamoe.mirai.message.data.Face.ZHUAN_QUAN;
            case KE_TOU:
                return net.mamoe.mirai.message.data.Face.KE_TOU;
            case HUI_TOU:
                return net.mamoe.mirai.message.data.Face.HUI_TOU;
            case TIAO_SHENG:
                return net.mamoe.mirai.message.data.Face.TIAO_SHENG;
            case HUI_SHOU:
                return net.mamoe.mirai.message.data.Face.HUI_SHOU;
            case JI_DONG:
                return net.mamoe.mirai.message.data.Face.JI_DONG;
            case JIE_WU:
                return net.mamoe.mirai.message.data.Face.JIE_WU;
            case XIAN_WEN:
                return net.mamoe.mirai.message.data.Face.XIAN_WEN;
            case ZUO_TAI_JI:
                return net.mamoe.mirai.message.data.Face.ZUO_TAI_JI;
            case YOU_TAI_JI:
                return net.mamoe.mirai.message.data.Face.YOU_TAI_JI;
            case SHUANG_XI:
                return net.mamoe.mirai.message.data.Face.SHUANG_XI;
            case BIAN_PAO:
                return net.mamoe.mirai.message.data.Face.BIAN_PAO;
            case DENG_LONG:
                return net.mamoe.mirai.message.data.Face.DENG_LONG;
            case K_GE:
                return net.mamoe.mirai.message.data.Face.K_GE;
            case HE_CAI:
                return net.mamoe.mirai.message.data.Face.HE_CAI;
            case QI_DAO:
                return net.mamoe.mirai.message.data.Face.QI_DAO;
            case BAO_JIN:
                return net.mamoe.mirai.message.data.Face.BAO_JIN;
            case BANG_BANG_TANG:
                return net.mamoe.mirai.message.data.Face.BANG_BANG_TANG;
            case HE_NAI:
                return net.mamoe.mirai.message.data.Face.HE_NAI;
            case FEI_JI:
                return net.mamoe.mirai.message.data.Face.FEI_JI;
            case CHAO_PIAO:
                return net.mamoe.mirai.message.data.Face.CHAO_PIAO;
            case YAO:
                return net.mamoe.mirai.message.data.Face.YAO;
            case SHOU_QIANG:
                return net.mamoe.mirai.message.data.Face.SHOU_QIANG;
            case CHA:
                return net.mamoe.mirai.message.data.Face.CHA;
            case ZHA_YAN_JING:
                return net.mamoe.mirai.message.data.Face.ZHA_YAN_JING;
            case LEI_BEN:
                return net.mamoe.mirai.message.data.Face.LEI_BEN;
            case WU_NAI:
                return net.mamoe.mirai.message.data.Face.WU_NAI;
            case MAI_MENG:
                return net.mamoe.mirai.message.data.Face.MAI_MENG;
            case XIAO_JIU_JIE:
                return net.mamoe.mirai.message.data.Face.XIAO_JIU_JIE;
            case PEN_XIE:
                return net.mamoe.mirai.message.data.Face.PEN_XIE;
            case XIE_YAN_XIAO:
                return net.mamoe.mirai.message.data.Face.XIE_YAN_XIAO;
            case doge:
                return net.mamoe.mirai.message.data.Face.doge;
            case JING_XI:
                return net.mamoe.mirai.message.data.Face.JING_XI;
            case SAO_RAO:
                return net.mamoe.mirai.message.data.Face.SAO_RAO;
            case XIAO_KU:
                return net.mamoe.mirai.message.data.Face.XIAO_KU;
            case WO_ZUI_MEI:
                return net.mamoe.mirai.message.data.Face.WO_ZUI_MEI;
            case HE_XIE:
                return net.mamoe.mirai.message.data.Face.HE_XIE;
            case YANG_TUO:
                return net.mamoe.mirai.message.data.Face.YANG_TUO;
            case YOU_LING:
                return net.mamoe.mirai.message.data.Face.YOU_LING;
            case DAN:
                return net.mamoe.mirai.message.data.Face.DAN;
            case JU_HUA:
                return net.mamoe.mirai.message.data.Face.JU_HUA;
            case HONG_BAO:
                return net.mamoe.mirai.message.data.Face.HONG_BAO;
            case DA_XIAO:
                return net.mamoe.mirai.message.data.Face.DA_XIAO;
            case BU_KAI_XIN:
                return net.mamoe.mirai.message.data.Face.BU_KAI_XIN;
            case LENG_MO:
                return net.mamoe.mirai.message.data.Face.LENG_MO;
            case E:
                return net.mamoe.mirai.message.data.Face.E;
            case HAO_BANG:
                return net.mamoe.mirai.message.data.Face.HAO_BANG;
            case BAI_TUO:
                return net.mamoe.mirai.message.data.Face.BAI_TUO;
            case DIAN_ZAN:
                return net.mamoe.mirai.message.data.Face.DIAN_ZAN;
            case WU_LIAO:
                return net.mamoe.mirai.message.data.Face.WU_LIAO;
            case TUO_LIAN:
                return net.mamoe.mirai.message.data.Face.TUO_LIAN;
            case CHI:
                return net.mamoe.mirai.message.data.Face.CHI;
            case SONG_HUA:
                return net.mamoe.mirai.message.data.Face.SONG_HUA;
            case HAI_PA:
                return net.mamoe.mirai.message.data.Face.HAI_PA;
            case HUA_CHI:
                return net.mamoe.mirai.message.data.Face.HUA_CHI;
            case XIAO_YANG_ER:
                return net.mamoe.mirai.message.data.Face.XIAO_YANG_ER;
            case BIAO_LEI:
                return net.mamoe.mirai.message.data.Face.BIAO_LEI;
            case WO_BU_KAN:
                return net.mamoe.mirai.message.data.Face.WO_BU_KAN;
            case TUO_SAI:
                return net.mamoe.mirai.message.data.Face.TUO_SAI;
            case BO_BO:
                return net.mamoe.mirai.message.data.Face.BO_BO;
            case HU_LIAN:
                return net.mamoe.mirai.message.data.Face.HU_LIAN;
            case PAI_TOU:
                return net.mamoe.mirai.message.data.Face.PAI_TOU;
            case CHE_YI_CHE:
                return net.mamoe.mirai.message.data.Face.CHE_YI_CHE;
            case TIAN_YI_TIAN:
                return net.mamoe.mirai.message.data.Face.TIAN_YI_TIAN;
            case CENG_YI_CENG:
                return net.mamoe.mirai.message.data.Face.CENG_YI_CENG;
            case ZHUAI_ZHA_TIAN:
                return net.mamoe.mirai.message.data.Face.ZHUAI_ZHA_TIAN;
            case DING_GUA_GUA:
                return net.mamoe.mirai.message.data.Face.DING_GUA_GUA;
            case BAO_BAO:
                return net.mamoe.mirai.message.data.Face.BAO_BAO;
            case BAO_JI:
                return net.mamoe.mirai.message.data.Face.BAO_JI;
            case KAI_QIANG:
                return net.mamoe.mirai.message.data.Face.KAI_QIANG;
            case LIAO_YI_LIAO:
                return net.mamoe.mirai.message.data.Face.LIAO_YI_LIAO;
            case PAI_ZHUO:
                return net.mamoe.mirai.message.data.Face.PAI_ZHUO;
            case PAI_SHOU:
                return net.mamoe.mirai.message.data.Face.PAI_SHOU;
            case GONG_XI:
                return net.mamoe.mirai.message.data.Face.GONG_XI;
            case GAN_BEI:
                return net.mamoe.mirai.message.data.Face.GAN_BEI;
            case CHAO_FENG:
                return net.mamoe.mirai.message.data.Face.CHAO_FENG;
            case HENG:
                return net.mamoe.mirai.message.data.Face.HENG;
            case FO_XI:
                return net.mamoe.mirai.message.data.Face.FO_XI;
            case QIA_YI_QIA:
                return net.mamoe.mirai.message.data.Face.QIA_YI_QIA;
            case JING_DAI:
                return net.mamoe.mirai.message.data.Face.JING_DAI;
            case CHAN_DOU:
                return net.mamoe.mirai.message.data.Face.CHAN_DOU;
            case KEN_TOU:
                return net.mamoe.mirai.message.data.Face.KEN_TOU;
            case TOU_KAN:
                return net.mamoe.mirai.message.data.Face.TOU_KAN;
            case SHAN_LIAN:
                return net.mamoe.mirai.message.data.Face.SHAN_LIAN;
            case YUAN_LIANG:
                return net.mamoe.mirai.message.data.Face.YUAN_LIANG;
            case PEN_LIAN:
                return net.mamoe.mirai.message.data.Face.PEN_LIAN;
            case SHENG_RI_KUAI_LE:
                return net.mamoe.mirai.message.data.Face.SHENG_RI_KUAI_LE;
            case TOU_ZHUANG_JI:
                return net.mamoe.mirai.message.data.Face.TOU_ZHUANG_JI;
            case SHUAI_TOU:
                return net.mamoe.mirai.message.data.Face.SHUAI_TOU;
            case RENG_GOU:
                return net.mamoe.mirai.message.data.Face.RENG_GOU;
            case JIA_YOU_BI_SHENG:
                return net.mamoe.mirai.message.data.Face.JIA_YOU_BI_SHENG;
            case JIA_YOU_BAO_BAO:
                return net.mamoe.mirai.message.data.Face.JIA_YOU_BAO_BAO;
            case KOU_ZHAO_HU_TI:
                return net.mamoe.mirai.message.data.Face.KOU_ZHAO_HU_TI;
            case BAN_ZHUAN_ZHONG:
                return net.mamoe.mirai.message.data.Face.BAN_ZHUAN_ZHONG;
            case MANG_DAO_FEI_QI:
                return net.mamoe.mirai.message.data.Face.MANG_DAO_FEI_QI;
            case NAO_KUO_TENG:
                return net.mamoe.mirai.message.data.Face.NAO_KUO_TENG;
            case CANG_SANG:
                return net.mamoe.mirai.message.data.Face.CANG_SANG;
            case WU_LIAN:
                return net.mamoe.mirai.message.data.Face.WU_LIAN;
            case LA_YAN_JING:
                return net.mamoe.mirai.message.data.Face.LA_YAN_JING;
            case O_YO:
                return net.mamoe.mirai.message.data.Face.O_YO;
            case TOU_TU:
                return net.mamoe.mirai.message.data.Face.TOU_TU;
            case WEN_HAO_LIAN:
                return net.mamoe.mirai.message.data.Face.WEN_HAO_LIAN;
            case AN_ZHONG_GUAN_CHA:
                return net.mamoe.mirai.message.data.Face.AN_ZHONG_GUAN_CHA;
            case emm:
                return net.mamoe.mirai.message.data.Face.emm;
            case CHI_GUA:
                return net.mamoe.mirai.message.data.Face.CHI_GUA;
            case HE_HE_DA:
                return net.mamoe.mirai.message.data.Face.HE_HE_DA;
            case WO_SUAN_LE:
                return net.mamoe.mirai.message.data.Face.WO_SUAN_LE;
            case TAI_NAN_LE:
                return net.mamoe.mirai.message.data.Face.TAI_NAN_LE;
            case LA_JIAO_JIANG:
                return net.mamoe.mirai.message.data.Face.LA_JIAO_JIANG;
            case WANG_WANG:
                return net.mamoe.mirai.message.data.Face.WANG_WANG;
            case HAN:
                return net.mamoe.mirai.message.data.Face.HAN;
            case DA_LIAN:
                return net.mamoe.mirai.message.data.Face.DA_LIAN;
            case JI_ZHANG:
                return net.mamoe.mirai.message.data.Face.JI_ZHANG;
            case WU_YAN_XIAO:
                return net.mamoe.mirai.message.data.Face.WU_YAN_XIAO;
            case JING_LI:
                return net.mamoe.mirai.message.data.Face.JING_LI;
            case KUANG_XIAO:
                return net.mamoe.mirai.message.data.Face.KUANG_XIAO;
            case MIAN_WU_BIAO_QING:
                return net.mamoe.mirai.message.data.Face.MIAN_WU_BIAO_QING;
            case MO_YU:
                return net.mamoe.mirai.message.data.Face.MO_YU;
            case MO_GUI_XIAO:
                return net.mamoe.mirai.message.data.Face.MO_GUI_XIAO;
            case O:
                return net.mamoe.mirai.message.data.Face.O;
            case QING:
                return net.mamoe.mirai.message.data.Face.QING;
            case ZHENG_YAN:
                return net.mamoe.mirai.message.data.Face.ZHENG_YAN;
            case QIAO_KAI_XIN:
                return net.mamoe.mirai.message.data.Face.QIAO_KAI_XIN;
            case ZHEN_JING:
                return net.mamoe.mirai.message.data.Face.ZHEN_JING;
            case RANG_WO_KANG_KANG:
                return net.mamoe.mirai.message.data.Face.RANG_WO_KANG_KANG;
            case MO_JIN_LI:
                return net.mamoe.mirai.message.data.Face.MO_JIN_LI;
            case QI_DAI:
                return net.mamoe.mirai.message.data.Face.QI_DAI;
            case NA_DAO_HONG_BAO:
                return net.mamoe.mirai.message.data.Face.NA_DAO_HONG_BAO;
            case ZHEN_HAO:
                return net.mamoe.mirai.message.data.Face.ZHEN_HAO;
            case BAI_XIE:
                return net.mamoe.mirai.message.data.Face.BAI_XIE;
            case YUAN_BAO:
                return net.mamoe.mirai.message.data.Face.YUAN_BAO;
            case NIU_A:
                return net.mamoe.mirai.message.data.Face.NIU_A;
            case PANG_SAN_JIN:
                return net.mamoe.mirai.message.data.Face.PANG_SAN_JIN;
            case HAO_SHAN:
                return net.mamoe.mirai.message.data.Face.HAO_SHAN;
            case ZUO_BAI_NIAN:
                return net.mamoe.mirai.message.data.Face.ZUO_BAI_NIAN;
            case YOU_BAI_NIAN:
                return net.mamoe.mirai.message.data.Face.YOU_BAI_NIAN;
            case HONG_BAO_BAO:
                return net.mamoe.mirai.message.data.Face.HONG_BAO_BAO;
            case YOU_QIN_QIN:
                return net.mamoe.mirai.message.data.Face.YOU_QIN_QIN;
            case NIU_QI_CHONG_TIAN:
                return net.mamoe.mirai.message.data.Face.NIU_QI_CHONG_TIAN;
            case MIAO_MIAO:
                return net.mamoe.mirai.message.data.Face.MIAO_MIAO;
            case QIU_HONG_BAO:
                return net.mamoe.mirai.message.data.Face.QIU_HONG_BAO;
            case XIE_HONG_BAO:
                return net.mamoe.mirai.message.data.Face.XIE_HONG_BAO;
            case XIN_NIAN_YAN_HUA:
                return net.mamoe.mirai.message.data.Face.XIN_NIAN_YAN_HUA;
            case DA_CALL:
                return net.mamoe.mirai.message.data.Face.DA_CALL;
            case BIAN_XING:
                return net.mamoe.mirai.message.data.Face.BIAN_XING;
            case KE_DAO_LE:
                return net.mamoe.mirai.message.data.Face.KE_DAO_LE;
            case ZI_XI_FEN_XI:
                return net.mamoe.mirai.message.data.Face.ZI_XI_FEN_XI;
            case JIA_YOU:
                return net.mamoe.mirai.message.data.Face.JIA_YOU;
            case WO_MEI_SHI:
                return net.mamoe.mirai.message.data.Face.WO_MEI_SHI;
            case CAI_GOU:
                return net.mamoe.mirai.message.data.Face.CAI_GOU;
            case CHONG_BAI:
                return net.mamoe.mirai.message.data.Face.CHONG_BAI;
            case BI_XIN:
                return net.mamoe.mirai.message.data.Face.BI_XIN;
            case QING_ZHU:
                return net.mamoe.mirai.message.data.Face.QING_ZHU;
            case LAO_SE_PI:
                return net.mamoe.mirai.message.data.Face.LAO_SE_PI;
            case JU_JUE:
                return net.mamoe.mirai.message.data.Face.JU_JUE;
            case XIAN_QI:
                return net.mamoe.mirai.message.data.Face.XIAN_QI;
            case CHI_TANG:
                return net.mamoe.mirai.message.data.Face.CHI_TANG;
            default:
                throw new NoSuchElementException();
        }
    }
    
    /**
     * 将小明表情转化为 Mirai 表情
     *
     * @param face 小明表情
     * @return Mirai 表情
     */
    public static net.mamoe.mirai.message.data.Face toMirai(Face face) {
        return new net.mamoe.mirai.message.data.Face(toMiraiFaceId(face));
    }
    
    /**
     * 将 Mirai 表情转化为小明表情
     *
     * @param face Mirai 表情
     * @return 小明表情
     */
    @SuppressWarnings("all")
    public static Face fromMirai(net.mamoe.mirai.message.data.Face face) {
        Preconditions.objectNonNull(face, "face");
    
        switch (face.getId()) {
            case net.mamoe.mirai.message.data.Face.JING_YA:
                return Face.JING_YA;
            case net.mamoe.mirai.message.data.Face.PIE_ZUI:
                return Face.PIE_ZUI;
            case net.mamoe.mirai.message.data.Face.SE:
                return Face.SE;
            case net.mamoe.mirai.message.data.Face.FA_DAI:
                return Face.FA_DAI;
            case net.mamoe.mirai.message.data.Face.DE_YI:
                return Face.DE_YI;
            case net.mamoe.mirai.message.data.Face.LIU_LEI:
                return Face.LIU_LEI;
            case net.mamoe.mirai.message.data.Face.HAI_XIU:
                return Face.HAI_XIU;
            case net.mamoe.mirai.message.data.Face.BI_ZUI:
                return Face.BI_ZUI;
            case net.mamoe.mirai.message.data.Face.SHUI:
                return Face.SHUI;
            case net.mamoe.mirai.message.data.Face.DA_KU:
                return Face.DA_KU;
            case net.mamoe.mirai.message.data.Face.GAN_GA:
                return Face.GAN_GA;
            case net.mamoe.mirai.message.data.Face.FA_NU:
                return Face.FA_NU;
            case net.mamoe.mirai.message.data.Face.TIAO_PI:
                return Face.TIAO_PI;
            case net.mamoe.mirai.message.data.Face.ZI_YA:
                return Face.ZI_YA;
            case net.mamoe.mirai.message.data.Face.WEI_XIAO:
                return Face.WEI_XIAO;
            case net.mamoe.mirai.message.data.Face.NAN_GUO:
                return Face.NAN_GUO;
            case net.mamoe.mirai.message.data.Face.KU:
                return Face.KU;
            case net.mamoe.mirai.message.data.Face.ZHUA_KUANG:
                return Face.ZHUA_KUANG;
            case net.mamoe.mirai.message.data.Face.TU:
                return Face.TU;
            case net.mamoe.mirai.message.data.Face.TOU_XIAO:
                return Face.TOU_XIAO;
            case net.mamoe.mirai.message.data.Face.KE_AI:
                return Face.KE_AI;
            case net.mamoe.mirai.message.data.Face.BAI_YAN:
                return Face.BAI_YAN;
            case net.mamoe.mirai.message.data.Face.AO_MAN:
                return Face.AO_MAN;
            case net.mamoe.mirai.message.data.Face.JI_E:
                return Face.JI_E;
            case net.mamoe.mirai.message.data.Face.KUN:
                return Face.KUN;
            case net.mamoe.mirai.message.data.Face.JING_KONG:
                return Face.JING_KONG;
            case net.mamoe.mirai.message.data.Face.LIU_HAN:
                return Face.LIU_HAN;
            case net.mamoe.mirai.message.data.Face.HAN_XIAO:
                return Face.HAN_XIAO;
            case net.mamoe.mirai.message.data.Face.YOU_XIAN:
                return Face.YOU_XIAN;
            case net.mamoe.mirai.message.data.Face.FEN_DOU:
                return Face.FEN_DOU;
            case net.mamoe.mirai.message.data.Face.ZHOU_MA:
                return Face.ZHOU_MA;
            case net.mamoe.mirai.message.data.Face.YI_WEN:
                return Face.YI_WEN;
            case net.mamoe.mirai.message.data.Face.XU:
                return Face.XU;
            case net.mamoe.mirai.message.data.Face.YUN:
                return Face.YUN;
            case net.mamoe.mirai.message.data.Face.ZHE_MO:
                return Face.ZHE_MO;
            case net.mamoe.mirai.message.data.Face.SHUAI:
                return Face.SHUAI;
            case net.mamoe.mirai.message.data.Face.KU_LOU:
                return Face.KU_LOU;
            case net.mamoe.mirai.message.data.Face.QIAO_DA:
                return Face.QIAO_DA;
            case net.mamoe.mirai.message.data.Face.ZAI_JIAN:
                return Face.ZAI_JIAN;
            case net.mamoe.mirai.message.data.Face.FA_DOU:
                return Face.FA_DOU;
            case net.mamoe.mirai.message.data.Face.AI_QING:
                return Face.AI_QING;
            case net.mamoe.mirai.message.data.Face.TIAO_TIAO:
                return Face.TIAO_TIAO;
            case net.mamoe.mirai.message.data.Face.ZHU_TOU:
                return Face.ZHU_TOU;
            case net.mamoe.mirai.message.data.Face.YONG_BAO:
                return Face.YONG_BAO;
            case net.mamoe.mirai.message.data.Face.DAN_GAO:
                return Face.DAN_GAO;
            case net.mamoe.mirai.message.data.Face.SHAN_DIAN:
                return Face.SHAN_DIAN;
            case net.mamoe.mirai.message.data.Face.ZHA_DAN:
                return Face.ZHA_DAN;
            case net.mamoe.mirai.message.data.Face.DAO:
                return Face.DAO;
            case net.mamoe.mirai.message.data.Face.ZU_QIU:
                return Face.ZU_QIU;
            case net.mamoe.mirai.message.data.Face.BIAN_BIAN:
                return Face.BIAN_BIAN;
            case net.mamoe.mirai.message.data.Face.KA_FEI:
                return Face.KA_FEI;
            case net.mamoe.mirai.message.data.Face.FAN:
                return Face.FAN;
            case net.mamoe.mirai.message.data.Face.MEI_GUI:
                return Face.MEI_GUI;
            case net.mamoe.mirai.message.data.Face.DIAO_XIE:
                return Face.DIAO_XIE;
            case net.mamoe.mirai.message.data.Face.AI_XIN:
                return Face.AI_XIN;
            case net.mamoe.mirai.message.data.Face.XIN_SUI:
                return Face.XIN_SUI;
            case net.mamoe.mirai.message.data.Face.LI_WU:
                return Face.LI_WU;
            case net.mamoe.mirai.message.data.Face.TAI_YANG:
                return Face.TAI_YANG;
            case net.mamoe.mirai.message.data.Face.YUE_LIANG:
                return Face.YUE_LIANG;
            case net.mamoe.mirai.message.data.Face.ZAN:
                return Face.ZAN;
            case net.mamoe.mirai.message.data.Face.CAI:
                return Face.CAI;
            case net.mamoe.mirai.message.data.Face.WO_SHOU:
                return Face.WO_SHOU;
            case net.mamoe.mirai.message.data.Face.SHENG_LI:
                return Face.SHENG_LI;
            case net.mamoe.mirai.message.data.Face.FEI_WEN:
                return Face.FEI_WEN;
            case net.mamoe.mirai.message.data.Face.OU_HUO:
                return Face.OU_HUO;
            case net.mamoe.mirai.message.data.Face.XI_GUA:
                return Face.XI_GUA;
            case net.mamoe.mirai.message.data.Face.LENG_HAN:
                return Face.LENG_HAN;
            case net.mamoe.mirai.message.data.Face.CA_HAN:
                return Face.CA_HAN;
            case net.mamoe.mirai.message.data.Face.KOU_BI:
                return Face.KOU_BI;
            case net.mamoe.mirai.message.data.Face.GU_ZHANG:
                return Face.GU_ZHANG;
            case net.mamoe.mirai.message.data.Face.QIU_DA_LE:
                return Face.QIU_DA_LE;
            case net.mamoe.mirai.message.data.Face.HUAI_XIAO:
                return Face.HUAI_XIAO;
            case net.mamoe.mirai.message.data.Face.ZUO_HENG_HENG:
                return Face.ZUO_HENG_HENG;
            case net.mamoe.mirai.message.data.Face.YOU_HENG_HENG:
                return Face.YOU_HENG_HENG;
            case net.mamoe.mirai.message.data.Face.HA_QIAN:
                return Face.HA_QIAN;
            case net.mamoe.mirai.message.data.Face.BI_SHI:
                return Face.BI_SHI;
            case net.mamoe.mirai.message.data.Face.WEI_QU:
                return Face.WEI_QU;
            case net.mamoe.mirai.message.data.Face.KUAI_KU_LE:
                return Face.KUAI_KU_LE;
            case net.mamoe.mirai.message.data.Face.YIN_XIAN:
                return Face.YIN_XIAN;
            case net.mamoe.mirai.message.data.Face.QIN_QIN:
                return Face.QIN_QIN;
            case net.mamoe.mirai.message.data.Face.XIA:
                return Face.XIA;
            case net.mamoe.mirai.message.data.Face.KE_LIAN:
                return Face.KE_LIAN;
            case net.mamoe.mirai.message.data.Face.CAI_DAO:
                return Face.CAI_DAO;
            case net.mamoe.mirai.message.data.Face.PI_JIU:
                return Face.PI_JIU;
            case net.mamoe.mirai.message.data.Face.LAN_QIU:
                return Face.LAN_QIU;
            case net.mamoe.mirai.message.data.Face.PING_PANG:
                return Face.PING_PANG;
            case net.mamoe.mirai.message.data.Face.SHI_AI:
                return Face.SHI_AI;
            case net.mamoe.mirai.message.data.Face.PIAO_CHONG:
                return Face.PIAO_CHONG;
            case net.mamoe.mirai.message.data.Face.BAO_QUAN:
                return Face.BAO_QUAN;
            case net.mamoe.mirai.message.data.Face.GOU_YIN:
                return Face.GOU_YIN;
            case net.mamoe.mirai.message.data.Face.QUAN_TOU:
                return Face.QUAN_TOU;
            case net.mamoe.mirai.message.data.Face.CHA_JIN:
                return Face.CHA_JIN;
            case net.mamoe.mirai.message.data.Face.AI_NI:
                return Face.AI_NI;
            case net.mamoe.mirai.message.data.Face.NO:
                return Face.NO;
            case net.mamoe.mirai.message.data.Face.OK:
                return Face.OK;
            case net.mamoe.mirai.message.data.Face.ZHUAN_QUAN:
                return Face.ZHUAN_QUAN;
            case net.mamoe.mirai.message.data.Face.KE_TOU:
                return Face.KE_TOU;
            case net.mamoe.mirai.message.data.Face.HUI_TOU:
                return Face.HUI_TOU;
            case net.mamoe.mirai.message.data.Face.TIAO_SHENG:
                return Face.TIAO_SHENG;
            case net.mamoe.mirai.message.data.Face.HUI_SHOU:
                return Face.HUI_SHOU;
            case net.mamoe.mirai.message.data.Face.JI_DONG:
                return Face.JI_DONG;
            case net.mamoe.mirai.message.data.Face.JIE_WU:
                return Face.JIE_WU;
            case net.mamoe.mirai.message.data.Face.XIAN_WEN:
                return Face.XIAN_WEN;
            case net.mamoe.mirai.message.data.Face.ZUO_TAI_JI:
                return Face.ZUO_TAI_JI;
            case net.mamoe.mirai.message.data.Face.YOU_TAI_JI:
                return Face.YOU_TAI_JI;
            case net.mamoe.mirai.message.data.Face.SHUANG_XI:
                return Face.SHUANG_XI;
            case net.mamoe.mirai.message.data.Face.BIAN_PAO:
                return Face.BIAN_PAO;
            case net.mamoe.mirai.message.data.Face.DENG_LONG:
                return Face.DENG_LONG;
            case net.mamoe.mirai.message.data.Face.K_GE:
                return Face.K_GE;
            case net.mamoe.mirai.message.data.Face.HE_CAI:
                return Face.HE_CAI;
            case net.mamoe.mirai.message.data.Face.QI_DAO:
                return Face.QI_DAO;
            case net.mamoe.mirai.message.data.Face.BAO_JIN:
                return Face.BAO_JIN;
            case net.mamoe.mirai.message.data.Face.BANG_BANG_TANG:
                return Face.BANG_BANG_TANG;
            case net.mamoe.mirai.message.data.Face.HE_NAI:
                return Face.HE_NAI;
            case net.mamoe.mirai.message.data.Face.FEI_JI:
                return Face.FEI_JI;
            case net.mamoe.mirai.message.data.Face.CHAO_PIAO:
                return Face.CHAO_PIAO;
            case net.mamoe.mirai.message.data.Face.YAO:
                return Face.YAO;
            case net.mamoe.mirai.message.data.Face.SHOU_QIANG:
                return Face.SHOU_QIANG;
            case net.mamoe.mirai.message.data.Face.CHA:
                return Face.CHA;
            case net.mamoe.mirai.message.data.Face.ZHA_YAN_JING:
                return Face.ZHA_YAN_JING;
            case net.mamoe.mirai.message.data.Face.LEI_BEN:
                return Face.LEI_BEN;
            case net.mamoe.mirai.message.data.Face.WU_NAI:
                return Face.WU_NAI;
            case net.mamoe.mirai.message.data.Face.MAI_MENG:
                return Face.MAI_MENG;
            case net.mamoe.mirai.message.data.Face.XIAO_JIU_JIE:
                return Face.XIAO_JIU_JIE;
            case net.mamoe.mirai.message.data.Face.PEN_XIE:
                return Face.PEN_XIE;
            case net.mamoe.mirai.message.data.Face.XIE_YAN_XIAO:
                return Face.XIE_YAN_XIAO;
            case net.mamoe.mirai.message.data.Face.doge:
                return Face.doge;
            case net.mamoe.mirai.message.data.Face.JING_XI:
                return Face.JING_XI;
            case net.mamoe.mirai.message.data.Face.SAO_RAO:
                return Face.SAO_RAO;
            case net.mamoe.mirai.message.data.Face.XIAO_KU:
                return Face.XIAO_KU;
            case net.mamoe.mirai.message.data.Face.WO_ZUI_MEI:
                return Face.WO_ZUI_MEI;
            case net.mamoe.mirai.message.data.Face.HE_XIE:
                return Face.HE_XIE;
            case net.mamoe.mirai.message.data.Face.YANG_TUO:
                return Face.YANG_TUO;
            case net.mamoe.mirai.message.data.Face.YOU_LING:
                return Face.YOU_LING;
            case net.mamoe.mirai.message.data.Face.DAN:
                return Face.DAN;
            case net.mamoe.mirai.message.data.Face.JU_HUA:
                return Face.JU_HUA;
            case net.mamoe.mirai.message.data.Face.HONG_BAO:
                return Face.HONG_BAO;
            case net.mamoe.mirai.message.data.Face.DA_XIAO:
                return Face.DA_XIAO;
            case net.mamoe.mirai.message.data.Face.BU_KAI_XIN:
                return Face.BU_KAI_XIN;
            case net.mamoe.mirai.message.data.Face.LENG_MO:
                return Face.LENG_MO;
            case net.mamoe.mirai.message.data.Face.E:
                return Face.E;
            case net.mamoe.mirai.message.data.Face.HAO_BANG:
                return Face.HAO_BANG;
            case net.mamoe.mirai.message.data.Face.BAI_TUO:
                return Face.BAI_TUO;
            case net.mamoe.mirai.message.data.Face.DIAN_ZAN:
                return Face.DIAN_ZAN;
            case net.mamoe.mirai.message.data.Face.WU_LIAO:
                return Face.WU_LIAO;
            case net.mamoe.mirai.message.data.Face.TUO_LIAN:
                return Face.TUO_LIAN;
            case net.mamoe.mirai.message.data.Face.CHI:
                return Face.CHI;
            case net.mamoe.mirai.message.data.Face.SONG_HUA:
                return Face.SONG_HUA;
            case net.mamoe.mirai.message.data.Face.HAI_PA:
                return Face.HAI_PA;
            case net.mamoe.mirai.message.data.Face.HUA_CHI:
                return Face.HUA_CHI;
            case net.mamoe.mirai.message.data.Face.XIAO_YANG_ER:
                return Face.XIAO_YANG_ER;
            case net.mamoe.mirai.message.data.Face.BIAO_LEI:
                return Face.BIAO_LEI;
            case net.mamoe.mirai.message.data.Face.WO_BU_KAN:
                return Face.WO_BU_KAN;
            case net.mamoe.mirai.message.data.Face.TUO_SAI:
                return Face.TUO_SAI;
            case net.mamoe.mirai.message.data.Face.BO_BO:
                return Face.BO_BO;
            case net.mamoe.mirai.message.data.Face.HU_LIAN:
                return Face.HU_LIAN;
            case net.mamoe.mirai.message.data.Face.PAI_TOU:
                return Face.PAI_TOU;
            case net.mamoe.mirai.message.data.Face.CHE_YI_CHE:
                return Face.CHE_YI_CHE;
            case net.mamoe.mirai.message.data.Face.TIAN_YI_TIAN:
                return Face.TIAN_YI_TIAN;
            case net.mamoe.mirai.message.data.Face.CENG_YI_CENG:
                return Face.CENG_YI_CENG;
            case net.mamoe.mirai.message.data.Face.ZHUAI_ZHA_TIAN:
                return Face.ZHUAI_ZHA_TIAN;
            case net.mamoe.mirai.message.data.Face.DING_GUA_GUA:
                return Face.DING_GUA_GUA;
            case net.mamoe.mirai.message.data.Face.BAO_BAO:
                return Face.BAO_BAO;
            case net.mamoe.mirai.message.data.Face.BAO_JI:
                return Face.BAO_JI;
            case net.mamoe.mirai.message.data.Face.KAI_QIANG:
                return Face.KAI_QIANG;
            case net.mamoe.mirai.message.data.Face.LIAO_YI_LIAO:
                return Face.LIAO_YI_LIAO;
            case net.mamoe.mirai.message.data.Face.PAI_ZHUO:
                return Face.PAI_ZHUO;
            case net.mamoe.mirai.message.data.Face.PAI_SHOU:
                return Face.PAI_SHOU;
            case net.mamoe.mirai.message.data.Face.GONG_XI:
                return Face.GONG_XI;
            case net.mamoe.mirai.message.data.Face.GAN_BEI:
                return Face.GAN_BEI;
            case net.mamoe.mirai.message.data.Face.CHAO_FENG:
                return Face.CHAO_FENG;
            case net.mamoe.mirai.message.data.Face.HENG:
                return Face.HENG;
            case net.mamoe.mirai.message.data.Face.FO_XI:
                return Face.FO_XI;
            case net.mamoe.mirai.message.data.Face.QIA_YI_QIA:
                return Face.QIA_YI_QIA;
            case net.mamoe.mirai.message.data.Face.JING_DAI:
                return Face.JING_DAI;
            case net.mamoe.mirai.message.data.Face.CHAN_DOU:
                return Face.CHAN_DOU;
            case net.mamoe.mirai.message.data.Face.KEN_TOU:
                return Face.KEN_TOU;
            case net.mamoe.mirai.message.data.Face.TOU_KAN:
                return Face.TOU_KAN;
            case net.mamoe.mirai.message.data.Face.SHAN_LIAN:
                return Face.SHAN_LIAN;
            case net.mamoe.mirai.message.data.Face.YUAN_LIANG:
                return Face.YUAN_LIANG;
            case net.mamoe.mirai.message.data.Face.PEN_LIAN:
                return Face.PEN_LIAN;
            case net.mamoe.mirai.message.data.Face.SHENG_RI_KUAI_LE:
                return Face.SHENG_RI_KUAI_LE;
            case net.mamoe.mirai.message.data.Face.TOU_ZHUANG_JI:
                return Face.TOU_ZHUANG_JI;
            case net.mamoe.mirai.message.data.Face.SHUAI_TOU:
                return Face.SHUAI_TOU;
            case net.mamoe.mirai.message.data.Face.RENG_GOU:
                return Face.RENG_GOU;
            case net.mamoe.mirai.message.data.Face.JIA_YOU_BI_SHENG:
                return Face.JIA_YOU_BI_SHENG;
            case net.mamoe.mirai.message.data.Face.JIA_YOU_BAO_BAO:
                return Face.JIA_YOU_BAO_BAO;
            case net.mamoe.mirai.message.data.Face.KOU_ZHAO_HU_TI:
                return Face.KOU_ZHAO_HU_TI;
            case net.mamoe.mirai.message.data.Face.BAN_ZHUAN_ZHONG:
                return Face.BAN_ZHUAN_ZHONG;
            case net.mamoe.mirai.message.data.Face.MANG_DAO_FEI_QI:
                return Face.MANG_DAO_FEI_QI;
            case net.mamoe.mirai.message.data.Face.NAO_KUO_TENG:
                return Face.NAO_KUO_TENG;
            case net.mamoe.mirai.message.data.Face.CANG_SANG:
                return Face.CANG_SANG;
            case net.mamoe.mirai.message.data.Face.WU_LIAN:
                return Face.WU_LIAN;
            case net.mamoe.mirai.message.data.Face.LA_YAN_JING:
                return Face.LA_YAN_JING;
            case net.mamoe.mirai.message.data.Face.O_YO:
                return Face.O_YO;
            case net.mamoe.mirai.message.data.Face.TOU_TU:
                return Face.TOU_TU;
            case net.mamoe.mirai.message.data.Face.WEN_HAO_LIAN:
                return Face.WEN_HAO_LIAN;
            case net.mamoe.mirai.message.data.Face.AN_ZHONG_GUAN_CHA:
                return Face.AN_ZHONG_GUAN_CHA;
            case net.mamoe.mirai.message.data.Face.emm:
                return Face.emm;
            case net.mamoe.mirai.message.data.Face.CHI_GUA:
                return Face.CHI_GUA;
            case net.mamoe.mirai.message.data.Face.HE_HE_DA:
                return Face.HE_HE_DA;
            case net.mamoe.mirai.message.data.Face.WO_SUAN_LE:
                return Face.WO_SUAN_LE;
            case net.mamoe.mirai.message.data.Face.TAI_NAN_LE:
                return Face.TAI_NAN_LE;
            case net.mamoe.mirai.message.data.Face.LA_JIAO_JIANG:
                return Face.LA_JIAO_JIANG;
            case net.mamoe.mirai.message.data.Face.WANG_WANG:
                return Face.WANG_WANG;
            case net.mamoe.mirai.message.data.Face.HAN:
                return Face.HAN;
            case net.mamoe.mirai.message.data.Face.DA_LIAN:
                return Face.DA_LIAN;
            case net.mamoe.mirai.message.data.Face.JI_ZHANG:
                return Face.JI_ZHANG;
            case net.mamoe.mirai.message.data.Face.WU_YAN_XIAO:
                return Face.WU_YAN_XIAO;
            case net.mamoe.mirai.message.data.Face.JING_LI:
                return Face.JING_LI;
            case net.mamoe.mirai.message.data.Face.KUANG_XIAO:
                return Face.KUANG_XIAO;
            case net.mamoe.mirai.message.data.Face.MIAN_WU_BIAO_QING:
                return Face.MIAN_WU_BIAO_QING;
            case net.mamoe.mirai.message.data.Face.MO_YU:
                return Face.MO_YU;
            case net.mamoe.mirai.message.data.Face.MO_GUI_XIAO:
                return Face.MO_GUI_XIAO;
            case net.mamoe.mirai.message.data.Face.O:
                return Face.O;
            case net.mamoe.mirai.message.data.Face.QING:
                return Face.QING;
            case net.mamoe.mirai.message.data.Face.ZHENG_YAN:
                return Face.ZHENG_YAN;
            case net.mamoe.mirai.message.data.Face.QIAO_KAI_XIN:
                return Face.QIAO_KAI_XIN;
            case net.mamoe.mirai.message.data.Face.ZHEN_JING:
                return Face.ZHEN_JING;
            case net.mamoe.mirai.message.data.Face.RANG_WO_KANG_KANG:
                return Face.RANG_WO_KANG_KANG;
            case net.mamoe.mirai.message.data.Face.MO_JIN_LI:
                return Face.MO_JIN_LI;
            case net.mamoe.mirai.message.data.Face.QI_DAI:
                return Face.QI_DAI;
            case net.mamoe.mirai.message.data.Face.NA_DAO_HONG_BAO:
                return Face.NA_DAO_HONG_BAO;
            case net.mamoe.mirai.message.data.Face.ZHEN_HAO:
                return Face.ZHEN_HAO;
            case net.mamoe.mirai.message.data.Face.BAI_XIE:
                return Face.BAI_XIE;
            case net.mamoe.mirai.message.data.Face.YUAN_BAO:
                return Face.YUAN_BAO;
            case net.mamoe.mirai.message.data.Face.NIU_A:
                return Face.NIU_A;
            case net.mamoe.mirai.message.data.Face.PANG_SAN_JIN:
                return Face.PANG_SAN_JIN;
            case net.mamoe.mirai.message.data.Face.HAO_SHAN:
                return Face.HAO_SHAN;
            case net.mamoe.mirai.message.data.Face.ZUO_BAI_NIAN:
                return Face.ZUO_BAI_NIAN;
            case net.mamoe.mirai.message.data.Face.YOU_BAI_NIAN:
                return Face.YOU_BAI_NIAN;
            case net.mamoe.mirai.message.data.Face.HONG_BAO_BAO:
                return Face.HONG_BAO_BAO;
            case net.mamoe.mirai.message.data.Face.YOU_QIN_QIN:
                return Face.YOU_QIN_QIN;
            case net.mamoe.mirai.message.data.Face.NIU_QI_CHONG_TIAN:
                return Face.NIU_QI_CHONG_TIAN;
            case net.mamoe.mirai.message.data.Face.MIAO_MIAO:
                return Face.MIAO_MIAO;
            case net.mamoe.mirai.message.data.Face.QIU_HONG_BAO:
                return Face.QIU_HONG_BAO;
            case net.mamoe.mirai.message.data.Face.XIE_HONG_BAO:
                return Face.XIE_HONG_BAO;
            case net.mamoe.mirai.message.data.Face.XIN_NIAN_YAN_HUA:
                return Face.XIN_NIAN_YAN_HUA;
            case net.mamoe.mirai.message.data.Face.DA_CALL:
                return Face.DA_CALL;
            case net.mamoe.mirai.message.data.Face.BIAN_XING:
                return Face.BIAN_XING;
            case net.mamoe.mirai.message.data.Face.KE_DAO_LE:
                return Face.KE_DAO_LE;
            case net.mamoe.mirai.message.data.Face.ZI_XI_FEN_XI:
                return Face.ZI_XI_FEN_XI;
            case net.mamoe.mirai.message.data.Face.JIA_YOU:
                return Face.JIA_YOU;
            case net.mamoe.mirai.message.data.Face.WO_MEI_SHI:
                return Face.WO_MEI_SHI;
            case net.mamoe.mirai.message.data.Face.CAI_GOU:
                return Face.CAI_GOU;
            case net.mamoe.mirai.message.data.Face.CHONG_BAI:
                return Face.CHONG_BAI;
            case net.mamoe.mirai.message.data.Face.BI_XIN:
                return Face.BI_XIN;
            case net.mamoe.mirai.message.data.Face.QING_ZHU:
                return Face.QING_ZHU;
            case net.mamoe.mirai.message.data.Face.LAO_SE_PI:
                return Face.LAO_SE_PI;
            case net.mamoe.mirai.message.data.Face.JU_JUE:
                return Face.JU_JUE;
            case net.mamoe.mirai.message.data.Face.XIAN_QI:
                return Face.XIAN_QI;
            case net.mamoe.mirai.message.data.Face.CHI_TANG:
                return Face.CHI_TANG;
            default:
                throw new NoSuchElementException();
        }
    }
}
